### PR TITLE
DM-30651: Switch DECam overscan correction to median per row

### PR DESCRIPTION
**Pull request by leeskelvin**

### CODE REVIEW

**Review by kherner — APPROVED** [review]
Looks fine, so approved pending a successful CI run.

**Comment by leeskelvin** [comment]
@RobertLuptonTheGood , thanks for that feedback. I've just ran several tests on a single DECam detector, just running ISR, and I don't see a noticeable difference in the data processing times. Both my MEDIAN and MEDIAN_PER_ROW runs ran in ~15 seconds. If anything, the MEDIAN runs seemed to exhibit more scatter (i.e., both returning my fastest processing time and my slowest processing time, all on the same detector). With this in mind, do you think it's okay to proceed ahead with this change for now, and address optimising MEDIAN_PER_ROW down the line if needs be?

**Comment by RobertLuptonTheGood** [comment]
That's surprising (and disturbingly slow, but that's a different matter).  I think it's worth checking if the good per-row code is running (it's a little tricky as the data's been floated before it's processed and the "clever" code is only needed for ints).

**Comment by leeskelvin** [comment]
From what I can tell, the MEDIAN/MEDIAN_PER_ROW logic kicks in on [L136 here](https://github.com/lsst/ip_isr/blob/9cb75138f37ebcc4baee52d337566964e5778068/python/lsst/ip/isr/overscan.py#L136). If MEDIAN_PER_ROW is requested, then the `measureVectorOverscan` method is run on [L439 here](https://github.com/lsst/ip_isr/blob/9cb75138f37ebcc4baee52d337566964e5778068/python/lsst/ip/isr/overscan.py#L439). From what I can tell, this seems to then call `collapseArrayMedian` for all MEDIAN_PER_ROW requests on [L329 here](https://github.com/lsst/ip_isr/blob/9cb75138f37ebcc4baee52d337566964e5778068/python/lsst/ip/isr/overscan.py#L329). Within this method, which part links to the issue you raise above @RobertLuptonTheGood ?

**Pull request merged**
